### PR TITLE
Added Community Detection for Undirected graphs

### PR DESCRIPTION
**Pull request by LibraChris**
Added the option to use community optimization based on  _Fast unfolding of communities in large networks; Vincent D Blondel Jean-Loup Guillaume Renaud Lambiotte Etienne Lefebvre ; 2008._

### CODE REVIEW

**Comment by HLWeil** [comment]
Could you add a little documentation and tests?

**Comment by HLWeil** [comment]
It seems like you included some code used for testing. Could you clean that out?

**Comment by LibraChris** [comment]
- Updated Louvain to keep original communities and add the new aggregated communities as a second element in the 'Label
- Added a Randomizer, that allows Louvain to randomize its community aggregation
- Updated ArrayAdjacencyGraph to subject the functions to the same scheme

**Comment by HLWeil** [comment]
Nice, but could you try to reduce code duplication? Maybe add one generic version of the function that both the randomized and unrandomized versions can reference

**Comment by HLWeil** [comment]
🚀

**Pull request merged**
